---
title: "Individual-Assignment-5"
author: "Macey Hartmann"
date: "2026-05-10"
format: pdf
execute:
  message: false
  warning: false
---

# Set up

## Packages

```{r}
#| label: packages

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrapping axis labels
library(scales)

# reading in .xlsx files
library(readxl)

# visualizing missing data
library(naniar)

# arranging plots
library(patchwork)
```

## Data

```{r}
#| label: data

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects")

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+"))

```

# 1. Visualizing differences across sites in major taxon abundance

## a. Plan your figure

- x-axis: `site_full`   
- y-axis: `log_ave_lit`  
- geometry to represent average abundance/L: `geom_jitter()` 
- geometry to represent medians: `stat_summary()` 

## b. Wrangle your data




